/* 深空来信 — original fan-made study companion. All narrative is locally scripted. */
(() => {
'use strict';
const S = window.CompanionStore, C = window.CompanionContent;
const $ = (s, parent=document) => parent.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
 star:'M12 2 15 9 22 12 15 15 12 22 9 15 2 12 9 9Z',
 home:'M3 11 12 3 21 11M5 10v11h14V10M9 21v-7h6v7',
 book:'M12 5c-3-3-7-3-10-1v15c4-2 7-1 10 1m0-15c3-3 7-3 10-1v15c-4-2-7-1-10 1V5',
 heart:'M20.5 4.8a5.5 5.5 0 0 0-8 0l-.5.6-.5-.6a5.5 5.5 0 0 0-8 7.6L12 21l8.5-8.6a5.5 5.5 0 0 0 0-7.6Z',
 memory:'M3 5h18v16H3zM2 2h20v3H2M9 10h6M9 15h6',
 cup:'M5 8h13v9a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V8m13 1h2a3 3 0 0 1 0 6h-2M8 2v3m4-4v4m4-3v3',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
 clock:'M12 8v5l3 2M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',
 arrow:'M4 12h16m-6-6 6 6-6 6',
 play:'M8 4 20 12 8 20Z',pause:'M8 4v16M16 4v16',
 leaf:'M20 3C5 2 1 11 7 17s15-1 13-14ZM5 20 15 10',
 moon:'M20 15A9 9 0 0 1 9 4 9 9 0 1 0 20 15Z',
 sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',
 sound:'M4 9h4l5-4v14l-5-4H4ZM16 8c3 2 3 6 0 8m3-11c5 4 5 10 0 14',
 mute:'M4 9h4l5-4v14l-5-4H4ZM17 9l5 6m0-6-5 6',
 expand:'M3 9V3h6m6 0h6v6M3 15v6h6m6 0h6v-6',
 pin:'M12 22s7-8 7-14a7 7 0 0 0-14 0c0 6 7 14 7 14Zm0-17a3 3 0 1 0 0 6 3 3 0 0 0 0-6',
 chat:'M21 3H3v14h4v5l6-5h8Z',
 hand:'M8 12V5a2 2 0 0 1 4 0v6-8a2 2 0 0 1 4 0v8-6a2 2 0 0 1 4 0v10c0 5-3 7-7 7-4 0-6-3-7-5l-3-5a2 2 0 0 1 3-2l2 2',
 plus:'M12 5v14M5 12h14',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',
 lock:'M5 10h14v11H5ZM8 10V6a4 4 0 0 1 8 0v4M12 14v3',check:'M4 12l5 5L20 6',
 mail:'M3 5h18v14H3ZM3 5l9 8 9-8',game:'M7 8h10c5 0 6 12 2 12l-4-4H9l-4 4C1 20 2 8 7 8ZM6 11v4m-2-2h4m8-1h.1m2 2h.1',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
};
const icon = (name) => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.star}"/></svg>`;
const uid=()=>S.state().selected, profile=()=>S.profile(), char=()=>C[uid()];
let currentView='home', duration=25, category='科研', taskId=null, taskDraft='', sceneMode='studio', immersive=false;
let lastReply='', dialogKind='', toastTimer, typingTimer, soundCtx=null, soundNodes=[], soundOn=false;
let lastNudge=Date.now(), typeVersion=0, tickBusy=false;
let scenePlayer=null;
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
const motionReduced=()=>!S.state().settings.motion||motionPreference.matches;
let sceneClips=Object.fromEntries(['qiyu','xinghui'].map(id=>[id,[{id:`${id}-gaze`,label:id==='qiyu'?'抬眼 · 在你身边':'暖光 · 安静相伴',src:`assets/clips/${id}-original-gaze.mp4`,poster:`assets/${id}-scene.jpg`}]]));
const pendingResults=[];
const relationshipNames=['初见的微光','渐近的心跳','默契的日常','偏爱的轨道','只属于我们的星海'];
const templates=[
 {name:'读一篇论文',category:'科研',title:'读懂一篇论文的核心问题',desc:'问题 → 方法 → 证据 → 我的疑问',steps:['写下论文试图回答的一个问题','用三句话概括方法与关键证据','记录一个局限，和一个值得继续问的问题']},
 {name:'推进一个实验',category:'科研',title:'让一个实验向前走一步',desc:'假设 → 最小实验 → 结果记录',steps:['明确这次实验的假设与判断标准','运行一个最小可验证的实验','记录结果、异常与下一步，不急着下结论']},
 {name:'写一小段论文',category:'写作',title:'完成一个段落的初稿',desc:'提纲 → 粗稿 → 引用核对',steps:['只写这段要传达的一个核心观点','写一版不追求完美的初稿','核对引用与论证，标出待补证据']},
 {name:'攻克一个知识点',category:'学习',title:'真正弄懂一个知识点',desc:'回忆 → 练习 → 复述',steps:['不看资料，写出目前能记住的内容','完成一题练习并找到卡点','用自己的话向他解释这个知识点']}
];
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3600);}
function dateText(){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long',timeZone:uid()==='qiyu'?'America/Chicago':'Asia/Shanghai'}).format(new Date());}
function mount(){
 $('#app').innerHTML=`<header class="topbar"><a href="#" class="brand" aria-label="深空来信主页"><span class="brand-star">✦</span><span><strong>深空来信</strong><small>LET OUR DAYS BECOME A STORY</small></span></a><div class="top-note"><span class="date" id="todayDate"></span><span class="save-status" id="saveStatus"><i class="status-dot"></i>已在此设备保存</span><button class="icon-btn" data-action="settings" aria-label="偏好与存档">${icon('settings')}</button><span class="avatar-initial" id="userInitial">B</span></div></header>
 <div class="app-layout"><aside class="sidebar" aria-label="主导航">
 ${[['home','home','此刻相伴'],['tasks','book','研究手记'],['stories','heart','心动剧场'],['memories','memory','回忆匣']].map(([v,i,t])=>`<button class="nav-item ${v==='home'?'active':''}" data-view="${v}">${icon(i)}<span>${t}</span></button>`).join('')}
 <a class="nav-item" href="../index.html" target="_blank" rel="noopener">${icon('cup')}<span>奶茶小铺</span></a>
 <div class="sidebar-end"><button class="nav-item" data-action="about">${icon('star')}<span>关于这里</span></button></div></aside>
 <main class="page"><div class="page-heading"><div><div class="eyebrow" id="pageEyebrow">OUR LITTLE ORBIT / 01</div><h1 class="serif" id="pageTitle">把今天，慢慢过成喜欢的样子。</h1></div><div class="profile-switch" aria-label="选择陪伴角色">${['qiyu','xinghui'].map(id=>`<button class="profile-btn" data-profile="${id}"><img class="profile-thumb" src="assets/${id}-portrait.jpg" alt=""><span>${C[id].name}<small>${id==='qiyu'?'Bedi 的专属陪伴':'Zhai 的专属陪伴'}</small></span></button>`).join('')}</div></div>
 <div id="homeView"><div class="home-grid"><section class="scene" id="scene" aria-label="角色陪伴场景">
 <div class="scene-bg"></div><video class="character-video" id="characterVideo" muted playsinline preload="auto"></video><div class="scene-wash"></div>
 <div class="scene-top"><span class="place-tag" id="placeTag"></span><div class="scene-tools"><button class="icon-btn" id="soundToggle" title="播放海浪环境音" aria-label="播放海浪环境音">${icon('mute')}</button><button class="icon-btn" id="sceneSettings" aria-label="更换氛围">${icon('sun')}</button><button class="icon-btn" id="immersiveToggle" aria-label="进入沉浸模式">${icon('expand')}</button></div></div>
 <div class="scene-playback" aria-label="陪伴镜头"><div class="scene-clip-caption"><span id="sceneClipName">此刻，在你身边</span><small id="scenePlaybackStatus" role="status" aria-live="polite">自然轮播</small></div><div class="scene-playback-actions"><button id="sceneLoop" type="button" aria-pressed="false" title="让喜欢的这一幕轻轻循环">${icon('pin')}<span>留在此刻</span></button><button id="sceneNext" type="button" title="看完这一刻，再进入下一镜"><span>下一镜</span>${icon('arrow')}</button></div></div>
 <div class="immersive-clock"><span id="immersiveDigits">25:00</span><button id="immersiveFocusButton">开始专注</button></div><div class="scene-name"><div class="eyebrow" id="characterEnglish"></div><h2 id="characterName"></h2><div class="little-line"></div><p id="characterMotto"></p></div>
 <button class="character-touch" id="characterTouch" aria-label="轻轻碰一下他"></button><button class="touch-cue" data-action="hand">${icon('hand')}<span>把手借给我</span></button>
 <div class="particles" aria-hidden="true">${Array.from({length:13},(_,i)=>`<i style="--x:${(i*31+7)%94}%;--y:${(i*23+10)%75}%;--d:${i*.6}s"></i>`).join('')}</div>
 <div class="scene-dialogue"><div class="speaker"><span id="speakerName"></span><small id="speakerAction"></small></div><p class="dialogue-line" id="dialogueLine" aria-live="polite"></p><div class="dialogue-actions"><button data-action="chat">${icon('chat')}陪我一会儿</button><button data-action="tired">${icon('moon')}有点累了</button><button data-action="game">${icon('game')}休息小游戏</button><button class="more-chat" data-action="openChat">说点什么 ${icon('arrow')}</button></div></div>
 </section><aside class="focus-panel"><div class="panel-title">${icon('clock')}一起，把这件事做好</div><p class="focus-subtitle">你向前一点点，他一直在身边。</p>
 <div class="category-tabs" aria-label="专注类别">${['科研','学习','写作'].map(c=>`<button data-category="${c}" class="${c===category?'active':''}">${c}</button>`).join('')}</div><input class="focus-task" id="focusTask" maxlength="100" aria-label="本次专注任务" placeholder="这一段，你想推进什么？">
 <div class="clock-block"><div class="timer-caption" id="timerCaption">A LITTLE TIME, JUST FOR US</div><div class="timer-digits" id="timerDigits" role="timer">25:00</div><div class="timer-status"><i class="status-dot"></i><span id="timerStatus">他已经为你留好了位置</span></div></div>
 <div class="time-presets" aria-label="专注时长">${[15,25,50].map(n=>`<button data-duration="${n}" class="${n===duration?'active':''}">${n} 分钟</button>`).join('')}<input type="number" id="customDuration" min="1" max="120" step="1" placeholder="自定" aria-label="自定义分钟数（1至120）"></div>
 <button class="primary full focus-start" id="focusStart">${icon('play')}开始我们的专注</button><div class="timer-secondary" id="timerSecondary" hidden><button id="finishEarly">结束并保存</button><button data-action="stuck">我卡住了</button></div>
 <p class="focus-reward" id="focusReward">每 5 分钟收集一枚星屑 · 点亮新的约定</p><div class="focus-note">${icon('leaf')}<p><strong id="focusNoteTitle">今天也可以，从很小的事开始</strong><span id="focusNote">不用一下子做完。先写下一个问题，我们一起看。</span></p></div>
 <div class="focus-footer"><div><span>今日相伴</span><b><span id="todayMinutes">0</span><small>分钟</small></b></div><i class="divider"></i><div><span>收集星屑</span><b><span id="fragmentCount">0</span><small>✦</small></b></div><i class="divider"></i><div><span>完成任务</span><b><span id="taskCount">0</span><small>项</small></b></div></div></aside></div>
 <div class="below-grid"><section class="mini-card"><div class="card-heading"><h3>${icon('book')}今日的小小进展</h3><button class="text-btn" data-view="tasks">研究手记 ${icon('arrow')}</button></div><div id="miniTasks"></div></section>
 <section class="mini-card story-preview"><div class="card-heading"><h3>${icon('mail')}下一封，心动来信</h3><span class="eyebrow">STORY</span></div><div id="nextStory"></div></section>
 <section class="mini-card bond-card"><div class="card-heading"><h3>${icon('heart')}我们的距离</h3><span class="eyebrow">BOND</span></div><div class="bond-main"><span class="bond-level" id="bondLevel"></span><span class="bond-icon">✧</span></div><div class="progress-track"><div class="progress-fill" id="bondFill"></div></div><div class="bond-caption"><span id="bondName"></span><span id="bondCount"></span></div></section></div></div>
 <div id="subView" class="subview" hidden></div><footer class="bottom-note"><span>不必每一天都闪闪发光。你来到这里，就已经很好。</span><span>原创同人陪伴 · 本机存档 <button class="text-btn" data-action="about">关于这里 ↗</button></span></footer></main></div>`;
 bindApp(); applyCharacter(false); updateStats(); updateTimer();
}
function setView(v){if(!['home','tasks','stories','memories'].includes(v))return; currentView=v; if(immersive&&v!=='home')toggleImmersive(); $('#homeView').hidden=v!=='home';$('#subView').hidden=v==='home';document.querySelectorAll('[data-view]').forEach(b=>{if(b.classList.contains('nav-item')){b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-current',b.dataset.view===v?'page':'false');}}); const copy={home:['OUR LITTLE ORBIT / 01','把今天，慢慢过成喜欢的样子。'],tasks:['ONE SMALL STEP / 02','把很大的事，拆成走得动的小步。'],stories:['BETWEEN YOU AND ME / 03','有些心动，藏在普通的一天里。'],memories:['THE DAYS WE KEEP / 04','那些一起度过的时间，都有回声。']};$('#pageEyebrow').textContent=copy[v][0];$('#pageTitle').textContent=copy[v][1];renderSubview(); playVideo();window.scrollTo({top:0,behavior:'smooth'});}
function bindApp(){
 $('#app').addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.classList.contains('brand')){e.preventDefault();setView('home');}if(b.dataset.view)setView(b.dataset.view);if(b.dataset.profile)switchProfile(b.dataset.profile);if(b.dataset.action)action(b.dataset.action);if(b.dataset.duration){if(profile().timer)return;duration=+b.dataset.duration;$('#customDuration').value='';updateTimer();}if(b.dataset.category){if(profile().timer)return;category=b.dataset.category;updateTimer();}});
 $('#focusTask').addEventListener('input',e=>{taskDraft=e.target.value;taskId=null;});$('#customDuration').addEventListener('change',e=>{const n=+e.target.value;if(!Number.isInteger(n)||n<1||n>120){toast('自定义时长可以设为 1–120 分钟');e.target.value='';return;}duration=n;updateTimer();});
 $('#focusStart').onclick=handleTimer;$('#immersiveFocusButton').onclick=handleTimer;$('#finishEarly').onclick=confirmFinish;$('#characterTouch').onclick=()=>respond('touch');$('#soundToggle').onclick=toggleSound;$('#sceneSettings').onclick=openSceneSettings;$('#immersiveToggle').onclick=toggleImmersive;
 $('#closeDialog').onclick=closeDialog;$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});$('#dialog').addEventListener('close',()=>{if(!$('#dialog').open)dialogKind='';setTimeout(()=>{if(!$('#dialog').open&&pendingResults.length){const [result,id]=pendingResults.shift();sessionComplete(result,id);}},0);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&immersive&&!$('#dialog').open)toggleImmersive();});
 $('#sceneLoop').onclick=()=>{if(!scenePlayer)return;scenePlayer.setMode(scenePlayer.getCurrent().mode==='auto'?'loop':'auto');};
 $('#sceneNext').onclick=()=>{if(!scenePlayer)return;const info=scenePlayer.next();if(info.nextQueued)toast('看完这一刻，再一起走进下一镜。');};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){scenePlayer?.pause();if(soundCtx)soundCtx.suspend();}else{playVideo();if(soundCtx&&soundOn)soundCtx.resume();checkTimers();}});
 if(motionPreference.addEventListener)motionPreference.addEventListener('change',playVideo);
 window.addEventListener('pagehide',()=>scenePlayer?.pause());
 window.addEventListener('pageshow',playVideo);
}
function switchProfile(id){if(uid()===id)return;if(profile().timer&&!profile().timer.paused){S.pause();toast('已暂停这一段专注，随时可以回来继续。');}S.select(id);taskDraft='';taskId=null;category=profile().timer?.category||'科研';duration=profile().timer?profile().timer.durationMs/60000:25;applyCharacter(true);updateStats();updateTimer();renderSubview();}
function applyCharacter(animate=true){const c=char(),id=uid();$('#scene').dataset.character=id;$('#scene').style.setProperty('--scene-poster',`url(assets/${id}-scene.jpg)`);$('#characterName').textContent=c.name;$('#characterEnglish').textContent=c.english;$('#characterMotto').textContent=id==='qiyu'?'你的灵感，今天也由我保管。':'慢慢来。你的这一页，我陪你翻。';$('#speakerName').textContent=c.name;$('#todayDate').textContent=dateText();$('#userInitial').textContent=id==='qiyu'?'B':'Z';$('#focusTask').value=taskDraft;$('#scene').dataset.scene=sceneMode;setPlace();document.querySelectorAll('[data-profile]').forEach(b=>{b.classList.toggle('active',b.dataset.profile===id);b.setAttribute('aria-pressed',String(b.dataset.profile===id));}); syncScenePlayer(); const greet=typeof c.greeting==='string'?{line:c.greeting,action:'抬眼看向你'}:c.greeting;setDialogue(greet,animate);document.body.classList.toggle('reduced-motion',motionReduced());$('#saveStatus').innerHTML=S.persistence?'<i class="status-dot"></i>已在此设备保存':'暂未能保存 · 请导出备份';}
function setPlace(){const p=sceneMode==='night'?'夜色渐深 · 安静陪伴':sceneMode==='sea'?'听见海风 · 放松片刻':(uid()==='qiyu'?'白沙湾 · Mo Art Studio':'临空市 · 暖光书房');$('#placeTag').innerHTML=icon('pin')+esc(p);}
function updateSceneControls(info){
 if(!info)return;
 const clips=sceneClips[info.character]||[],name=$('#sceneClipName'),status=$('#scenePlaybackStatus'),stay=$('#sceneLoop'),next=$('#sceneNext');
 if(!name||!status||!stay||!next)return;
 name.textContent=info.clip?.label||clips[0]?.label||'此刻，在你身边';
 status.textContent=info.state==='unavailable'?'静态陪伴':info.reducedMotion?'静静陪伴':info.nextQueued?'这一刻过后，见下一镜':info.mode==='loop'?'留在喜欢的这一幕':'自然轮播';
 status.title=info.error||'';
 stay.innerHTML=icon(info.mode==='loop'?'play':'pin')+`<span>${info.mode==='loop'?'自然轮播':'留在此刻'}</span>`;
 stay.setAttribute('aria-pressed',String(info.mode==='loop'));
 stay.setAttribute('aria-label',info.mode==='loop'?'恢复自然轮播':'留在此刻，循环当前镜头');
 stay.disabled=info.reducedMotion||info.state==='unavailable';
 next.disabled=clips.length<2||info.nextQueued||info.state==='unavailable';
 next.setAttribute('aria-label',info.nextQueued?'下一镜已排队，当前片段结束后切换':'下一镜');
}
function syncScenePlayer(){
 const id=uid();
 if(!scenePlayer){
  scenePlayer=new window.CompanionScenePlayer({container:$('#scene'),character:id,clips:sceneClips[id],reduceMotion:motionReduced(),onClipChange:updateSceneControls});
 }else if(scenePlayer.getCurrent().character!==id){
  scenePlayer.setCharacter(id,sceneClips[id]);
 }
 updateSceneControls(scenePlayer.getCurrent());
 playVideo();
}
async function loadSceneClips(){
 try{
  const response=await fetch('assets/clips/manifest.json',{cache:'force-cache'});
  if(!response.ok)throw new Error('Scene manifest unavailable');
  const manifest=await response.json();
  for(const id of ['qiyu','xinghui']){
   if(Array.isArray(manifest[id])&&manifest[id].length&&manifest[id].every(clip=>clip&&typeof clip.src==='string'))sceneClips[id]=manifest[id];
  }
  if(scenePlayer){scenePlayer.setCharacter(uid(),sceneClips[uid()]);updateSceneControls(scenePlayer.getCurrent());playVideo();}
 }catch(_){/* A local single-scene fallback remains available when the manifest cannot load. */}
}
function playVideo(){
 const reduce=motionReduced();
 document.body.classList.toggle('reduced-motion',reduce);
 if(!scenePlayer)return;
 scenePlayer.setReducedMotion(reduce);
 if(currentView==='home'&&!document.hidden&&!reduce)scenePlayer.play();else scenePlayer.pause();
}
function setDialogue(reply,animate=true){if(!reply)return;const line=reply.line||String(reply), a=reply.action||'在你身边';$('#speakerAction').textContent=a;clearInterval(typingTimer);typeVersion++;const node=$('#dialogueLine');node.textContent='';if(!animate||!S.state().settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches){node.textContent=line;return;}let i=0;const ver=typeVersion;typingTimer=setInterval(()=>{if(ver!==typeVersion){clearInterval(typingTimer);return;}node.textContent=line.slice(0,++i);if(i>=line.length)clearInterval(typingTimer);},25);}
function replyFor(intent){let pool=char().actions[intent]||char().actions.chat;pool=pool.filter(r=>r.line!==lastReply);if(!pool.length)pool=char().actions[intent]||char().actions.chat;const reply=pool[Math.floor(Math.random()*pool.length)];lastReply=reply.line;return {...reply};}
function respond(intent,withReward=true){if(intent==='hand'&&!S.state().settings.romance)intent='encourage';const r=replyFor(intent);setDialogue(r);const scene=$('#scene');scene.classList.remove('reacting');void scene.offsetWidth;scene.classList.add('reacting');setTimeout(()=>scene.classList.remove('reacting'),1400);if(withReward){const gain=S.rewardInteraction(intent);if(gain.rewarded){updateStats();toast('今日的小小回应 · 羁绊 +2');}}return r;}
function action(a){if(['touch','hand','chat','tired','stuck','water','encourage'].includes(a)){if(a==='stuck'){openHelp();return;}if(a==='tired'){openRest();return;}respond(a);return;}({openChat,game:openGame,settings:openSettings,about:openAbout,addTask:openTaskForm}[a]||(()=>{}))();}
function updateStats(){const p=profile();$('#todayMinutes').textContent=S.todayMinutes();$('#fragmentCount').textContent=p.fragments;$('#taskCount').textContent=p.tasks.filter(t=>t.done).length;const lv=Math.floor(p.bond/100)+1;$('#bondLevel').innerHTML=`<small>Lv.</small>${lv}`;$('#bondFill').style.width=`${p.bond%100}%`;$('#bondCount').textContent=`${p.bond%100} / 100`;$('#bondName').textContent=relationshipNames[Math.min(lv-1,4)];const tasks=p.tasks.slice().sort((a,b)=>a.done-b.done).slice(0,2);$('#miniTasks').innerHTML=tasks.length?tasks.map(t=>`<div class="tiny-task ${t.done?'done':''}"><button class="task-check ${t.done?'done':''}" data-mini-task="${esc(t.id)}" aria-label="${t.done?'已完成':'标记完成'} ${esc(t.title)}" ${t.done?'disabled':''}>${t.done?'✓':''}</button><span class="tiny-title">${esc(t.title)}</span><span class="task-category">${esc(t.category)}</span></div>`).join(''):`<p class="empty-small">先选一件，今天想一起完成的小事。<button data-action="addTask">＋ 从一个小目标开始</button></p>`;$('#miniTasks').querySelectorAll('[data-mini-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.miniTask));const next=char().stories.find(st=>!p.storyRead.includes(st.id))||char().stories[0];const unlocked=p.minutes>=next.minutes;$('#nextStory').innerHTML=`<h4>${esc(next.title)}</h4><p>${unlocked?'信已经写好，等你来拆。':`再相伴 ${next.minutes-p.minutes} 分钟，这一页就会展开。`}</p><button class="text-btn" id="openNextStory">${unlocked?'拆开这封来信':'看看我们的约定'} ${icon('arrow')}</button>`;$('#openNextStory').onclick=()=>unlocked?openStory(next.id):setView('stories');}
function updateTimer(){const p=profile(),t=p.timer;let remaining=t?Math.max(0,t.durationMs-S.elapsed()):duration*60000;const sec=Math.ceil(remaining/1000);$('#timerDigits').textContent=`${Math.floor(sec/60).toString().padStart(2,'0')}:${(sec%60).toString().padStart(2,'0')}`;$('#timerStatus').textContent=t?(t.paused?'时间停在这里，等你回来':'安静陪伴中 · 正在积累真实专注'):'他已经为你留好了位置';$('#timerCaption').textContent=t?(t.paused?'TAKE YOUR TIME':'FOCUSING, TOGETHER'):'A LITTLE TIME, JUST FOR US';const btn=$('#focusStart');btn.innerHTML=icon(t&&!t.paused?'pause':'play')+(t?(t.paused?'回来，接着一起做':'暂停，喘口气'):'开始我们的专注');$('#immersiveDigits').textContent=$('#timerDigits').textContent;$('#immersiveFocusButton').textContent=t?(t.paused?'继续专注':'暂停片刻'):'开始专注';$('#timerSecondary').hidden=!t;$('#focusTask').disabled=!!t;$('#customDuration').disabled=!!t;document.querySelectorAll('[data-duration]').forEach(b=>{b.disabled=!!t;b.classList.toggle('active',+b.dataset.duration===(t?t.durationMs/60000:duration));});document.querySelectorAll('[data-category]').forEach(b=>{b.disabled=!!t;b.classList.toggle('active',b.dataset.category===(t?t.category:category));});if(t&&t.taskId){const task=p.tasks.find(x=>x.id===t.taskId);if(task)$('#focusTask').value=task.title;}}
function handleTimer(){const t=profile().timer;if(t){if(t.paused){S.resume();respond('return',false);}else{S.pause();respond('pause',false);}updateTimer();return;}if(!Number.isInteger(duration)||duration<1||duration>120)return;const title=$('#focusTask').value.trim();if(title&&!taskId){const task={id:cryptoId(),title,category,done:false,steps:[]};S.update(s=>s.profiles[s.selected].tasks.push(task));taskId=task.id;}const timer=S.start({minutes:duration,category,taskId});if(timer){lastNudge=Date.now();respond('start',false);updateTimer();updateStats();toast(`给自己 ${duration} 分钟。${char().name}陪你一起。`);}else toast('这一段暂时无法开始，请检查存档设置。');}
function confirmFinish(){showDialog(`<h2 class="modal-title" id="dialogTitle">把已经走过的路留下</h2><p class="modal-sub">提前结束会保存实际专注的整分钟。未满一分钟的时间不会计入奖励；任务由你确认完成。</p><div class="form-actions"><button class="secondary" id="keepFocus">继续专注</button><button class="primary" id="confirmFinish">结束并保存</button></div>`,'finish');$('#keepFocus').onclick=closeDialog;$('#confirmFinish').onclick=()=>{closeDialog();const result=S.finish();if(result)sessionComplete(result,uid());};}
function checkTimers(){if(tickBusy)return;tickBusy=true;try{for(const id of ['qiyu','xinghui']){const result=S.tick(id);if(result){if(id===uid())sessionComplete(result,id);else toast(`${C[id].name}陪伴的专注已保存。`);}}}finally{tickBusy=false;}updateTimer();if(profile().timer&&!profile().timer.paused&&Date.now()-lastNudge>8*60000){lastNudge=Date.now();if(!$('#dialog').open){const task=profile().tasks.find(x=>x.id===profile().timer.taskId);const r={...replyFor('encourage')};if(task)r.line=`${r.line} 这一段，我们只管「${task.title}」。`;setDialogue(r);}}}
function sessionComplete(result,id){S.update(s=>{const p=s.profiles[id];if(result.minutes>0&&!p.memories.some(m=>m.sessionId===result.id))p.memories.unshift({id:cryptoId(),sessionId:result.id,date:new Date().toISOString(),title:`一起专注了 ${result.minutes} 分钟`,text:'有些普通的日子，也值得被记住。',type:'focus'});});updateStats();updateTimer();if($('#dialog').open){pendingResults.push([result,id]);toast('这一段专注已保存。聊完这一页，再收下他的回应。');return;}respond('finish',false);if(soundOn)playChime();const c=C[id];showDialog(`<div class="celebrate"><div class="celebrate-symbol">✦</div><div class="eyebrow">A LITTLE CLOSER, TOGETHER</div><h2 id="dialogTitle">${result.completed?'这一程，我们一起走完了。':'今天的努力，已经好好收下。'}</h2><p>${esc(c.name)}把这一刻留进了你们的日常。</p><div class="session-result"><div><b>${result.minutes}</b><small>专注分钟</small></div><div><b>+${result.fragments}</b><small>星屑</small></div><div><b>+${result.bond}</b><small>羁绊</small></div></div><textarea class="reflection" id="reflection" maxlength="500" placeholder="留一句今天的进展：我发现了什么？下一步是什么？" aria-label="本次专注复盘"></textarea><button class="primary full" id="saveReflection">把这一页收进回忆匣</button><button class="text-btn" id="afterFocusRest">休息一下，和他聊聊天 ${icon('arrow')}</button></div>`,'result');$('#saveReflection').onclick=()=>{const note=$('#reflection').value.trim();S.update(s=>{const p=s.profiles[id];const existing=p.memories.find(m=>m.sessionId===result.id);if(existing){if(note)existing.text=note;}else if(note)p.memories.unshift({id:cryptoId(),sessionId:result.id,date:new Date().toISOString(),title:`一起专注了 ${result.minutes} 分钟`,text:note,type:'focus'});});closeDialog();toast('已收进回忆匣。');};$('#afterFocusRest').onclick=openRest;}
function cryptoId(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;}
function renderSubview(){if(currentView==='home')return;const el=$('#subView');if(currentView==='tasks')renderTasks(el);if(currentView==='stories')renderStories(el);if(currentView==='memories')renderMemories(el);}
function renderTasks(el){const p=profile();el.innerHTML=`<section class="section-intro"><div class="eyebrow">A SMALL, DOABLE PLAN</div><h2>科研没有进度条，我们就自己画一个。</h2><p>先拆成一个可以动手的步骤。${esc(char().name)}陪你读文献、做实验、写初稿，也陪你接纳暂时没想明白的部分。</p><div class="row"><button class="primary" data-new-task>${icon('plus')}添加小目标</button><button class="secondary" data-help>卡住了，帮我拆一下</button></div></section><div class="task-board">${p.tasks.length?p.tasks.map(t=>`<article class="task-card"><div class="task-top"><button class="task-check ${t.done?'done':''}" data-task-complete="${esc(t.id)}" aria-label="${t.done?'已完成':'标记完成'} ${esc(t.title)}" ${t.done?'disabled':''}>${t.done?'✓':''}</button><h3>${esc(t.title)}</h3><button class="icon-btn" data-task-delete="${esc(t.id)}" aria-label="删除 ${esc(t.title)}">${icon('trash')}</button></div><div class="task-steps">${t.steps.map((step,i)=>`<label><input type="checkbox" data-task-step="${esc(t.id)}" data-step-index="${i}" ${step.done?'checked':''} ${t.done?'disabled':''}>${esc(step.text)}</label>`).join('')}</div><div class="task-card-footer"><span class="pill">${esc(t.category)}${t.steps.length?` · ${t.steps.filter(x=>x.done).length}/${t.steps.length} 步`:''}</span><button class="text-btn" data-task-focus="${esc(t.id)}" ${t.done?'disabled':''}>一起推进 ${icon('arrow')}</button></div></article>`).join(''):`<section class="mini-card"><p class="empty-small">这里还没有任务。试试上面的「添加小目标」，选择适合你的科研或学习模板。</p></section>`}</div>`;el.querySelector('[data-new-task]').onclick=()=>openTaskForm();el.querySelector('[data-help]').onclick=openHelp;el.querySelectorAll('[data-task-complete]').forEach(b=>b.onclick=()=>completeTask(b.dataset.taskComplete));el.querySelectorAll('[data-task-step]').forEach(b=>b.onchange=()=>{S.update(s=>{s.profiles[s.selected].tasks.find(t=>t.id===b.dataset.taskStep).steps[+b.dataset.stepIndex].done=b.checked;});updateStats();renderSubview();});el.querySelectorAll('[data-task-focus]').forEach(b=>b.onclick=()=>{if(profile().timer){toast('先结束当前专注，再选择下一个目标。');return;}const t=profile().tasks.find(t=>t.id===b.dataset.taskFocus);taskId=t.id;taskDraft=t.title;category=t.category;$('#focusTask').value=t.title;setView('home');updateTimer();toast('目标已放到桌上，准备好就开始。');});el.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=()=>deleteTask(b.dataset.taskDelete));}
function openTaskForm(templateIndex){showDialog(`<h2 class="modal-title" id="dialogTitle">今天，先向前一小步</h2><p class="modal-sub">选一个起点，也可以完全按你的节奏来写。</p><div class="template-list">${templates.map((t,i)=>`<button data-template="${i}">${esc(t.name)}<small>${esc(t.desc)}</small></button>`).join('')}</div><form id="taskForm"><label class="form-label" for="taskTitle">这一件事叫什么？</label><input class="form-input" id="taskTitle" maxlength="100" required placeholder="例如：整理综述第二节的论证结构"><label class="form-label" for="taskCategory">属于哪种专注</label><select class="form-input" id="taskCategory"><option>科研</option><option>学习</option><option>写作</option></select><label class="form-label" for="taskSteps">拆成小步（每行一步，可留空）</label><textarea class="form-input" id="taskSteps" rows="4" maxlength="1000" placeholder="写下第一个能动手的动作"></textarea><div class="form-actions"><button type="submit" class="primary">把它放到我们的桌上 ${icon('arrow')}</button></div></form>`,'task');const fill=i=>{const t=templates[i];$('#taskTitle').value=t.title;$('#taskCategory').value=t.category;$('#taskSteps').value=t.steps.join('\n');};$('#dialogBody').querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>fill(+b.dataset.template));if(Number.isInteger(templateIndex))fill(templateIndex);$('#taskForm').onsubmit=e=>{e.preventDefault();const title=$('#taskTitle').value.trim();if(!title)return;const steps=$('#taskSteps').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,12).map(text=>({text,done:false}));const t={id:cryptoId(),title,category:$('#taskCategory').value,done:false,steps};if(profile().tasks.length>=100){toast('任务板最多放 100 项。先整理一下已完成的任务吧。');return;}S.update(s=>s.profiles[s.selected].tasks.push(t));closeDialog();updateStats();renderSubview();toast('新的小目标，已经放在桌上。');};}
function completeTask(id){const t=profile().tasks.find(x=>x.id===id);if(!t||t.done)return;S.update(s=>{const p=s.profiles[s.selected],task=p.tasks.find(x=>x.id===id);task.done=true;task.steps.forEach(st=>st.done=true);p.memories.unshift({id:cryptoId(),date:new Date().toISOString(),title:`完成了「${task.title}」`,text:`和${C[s.selected].name}一起，又往前走了一小步。`,type:'task'});});const reward=S.rewardInteraction('task-completion');updateStats();renderSubview();respond('finish',false);toast(`完成了「${t.title}」${reward.rewarded?' · 今日任务羁绊 +2':''}`);}
function deleteTask(id){const t=profile().tasks.find(x=>x.id===id);if(profile().timer?.taskId===id){toast('这项任务正在专注中，结束后再整理它。');return;}showDialog(`<h2 class="modal-title" id="dialogTitle">把这项任务移出桌面？</h2><p class="modal-sub">${esc(t.title)}<br>此前的专注时间与回忆仍会保留。</p><div class="form-actions"><button class="secondary" id="cancelDelete">先留下</button><button class="primary" id="deleteTask">移出桌面</button></div>`,'delete');$('#cancelDelete').onclick=closeDialog;$('#deleteTask').onclick=()=>{S.update(s=>s.profiles[s.selected].tasks=s.profiles[s.selected].tasks.filter(t=>t.id!==id));if(taskId===id){taskId=null;taskDraft='';$('#focusTask').value='';}closeDialog();renderSubview();updateStats();};}
function renderStories(el){const p=profile();el.innerHTML=`<section class="section-intro"><div class="eyebrow">LET'S MAKE ORDINARY DAYS SPECIAL</div><h2>和${esc(char().name)}，一起写下去。</h2><p>第一章已经为你展开。往后的约定会随真实的专注时间解锁。<br>每一次选择都有他的回应；读过的故事可以随时重温。</p><div class="stats-strip"><div><b>${p.storyRead.length} / 6</b><span>已珍藏的故事</span></div><div><b>${p.minutes}</b><span>一起走过的分钟</span></div></div></section><div class="story-grid">${char().stories.map((st,i)=>{const unlocked=p.minutes>=st.minutes,read=p.storyRead.includes(st.id);return `<article class="chapter-card"><div class="chapter-art"><img src="assets/${uid()}-${i%2?'card.png':'scene.jpg'}" alt="${esc(char().name)}的角色场景" loading="lazy"><span class="chapter-number">0${i+1}</span></div><div class="chapter-info"><h3>${esc(st.title)}</h3><p>${esc(st.subtitle)}</p><div class="chapter-lock">${icon(unlocked?'mail':'lock')}${read?'已珍藏 · 可以重温':unlocked?'已经为你展开':`再相伴 ${st.minutes-p.minutes} 分钟解锁`}</div><button class="${unlocked?'primary':'secondary'}" data-chapter="${esc(st.id)}" ${unlocked?'':'disabled'}>${read?'重温这一页':unlocked?'进入故事':'等待我们的下一次专注'}</button></div></article>`;}).join('')}</div>`;el.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>openStory(b.dataset.chapter));}
function openStory(id){const st=char().stories.find(x=>x.id===id);if(!st||profile().minutes<st.minutes)return;const charId=uid();let progress=profile().storyProgress[id]||{node:0,reply:null,next:null};if(!Number.isInteger(progress.node)||progress.node<0||progress.node>=st.nodes.length||(progress.next!==null&&progress.next!=='end'&&(!Number.isInteger(progress.next)||progress.next<0||progress.next>=st.nodes.length)))progress={node:0,reply:null,next:null};let node=progress.node;const advanceSave=()=>S.update(s=>s.profiles[charId].storyProgress[id]=progress);
 const draw=()=>{const n=st.nodes[node];showDialog(`<div class="story-player"><div class="chapter-art"><img src="assets/${charId}-card.png" alt="${esc(C[charId].name)}"><span class="chapter-number">${String(C[charId].stories.indexOf(st)+1).padStart(2,'0')}</span></div><div class="story-progress">${node+1} / ${st.nodes.length} · ORIGINAL SIDE STORY</div><h2 class="modal-title" id="dialogTitle">${esc(st.title)}</h2><p class="story-narration">${esc(n.text)}</p><div class="speaker">${esc(C[charId].name)}</div><p class="story-line">${esc(n.line)}</p>${progress.reply?`<div class="story-reply">${esc(progress.reply)}</div><button class="primary full" id="storyNext">${progress.next==='end'?'珍藏这一页':'继续听他说'} ${icon('arrow')}</button>`:`<div class="story-choices">${n.choices.map((c,i)=>`<button data-choice="${i}">${esc(c.label)}</button>`).join('')}</div>`}</div>`,'story');if(progress.reply){$('#storyNext').onclick=()=>{if(progress.next==='end'){const already=profile().storyRead.includes(id);S.update(s=>{const p=s.profiles[charId];if(!p.storyRead.includes(id)){p.storyRead.push(id);p.memories.unshift({id:cryptoId(),date:new Date().toISOString(),title:st.title,text:progress.reply,type:'story'});}delete p.storyProgress[id];});closeDialog();updateStats();renderSubview();toast(already?'又一起重温了这一页。':'这段故事，已经收进回忆匣。');return;}node=Number(progress.next);progress={node,reply:null,next:null};advanceSave();draw();};}else $('#dialogBody').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const choice=n.choices[+b.dataset.choice];progress={node,reply:choice.reply,next:choice.next};advanceSave();draw();});};draw();}
function renderMemories(el){const p=profile();el.innerHTML=`<section class="section-intro"><div class="eyebrow">NOTHING SMALL IS EVER LOST</div><h2>这些瞬间，我们都记得。</h2><p>完成的任务、亲手写下的复盘，以及故事里的那句回应，都可以在这里找到。</p><div class="stats-strip"><div><b>${p.minutes}</b><span>专注分钟</span></div><div><b>${p.sessions.length}</b><span>陪伴片段</span></div><div><b>${p.memories.length}</b><span>珍藏瞬间</span></div></div><button class="text-btn" id="exportJournal">${icon('download')}导出研究手记</button></section><div class="memory-grid">${p.memories.length?p.memories.map(m=>`<article class="memory"><time>${esc(new Date(m.date).toLocaleDateString('zh-CN'))} · ${m.type==='story'?'心动来信':m.type==='task'?'向前一小步':'相伴时光'}</time><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p></article>`).join(''):'<div class="mini-card"><p class="empty-small">回忆从一次真实的相伴开始。<br>去读第一封来信，或者给今天留一段专注时间。</p><button class="text-btn" id="firstMemory">打开第一封来信 →</button></div>'}</div>`;if($('#firstMemory'))$('#firstMemory').onclick=()=>openStory(char().stories[0].id);$('#exportJournal').onclick=()=>download(`和${char().name}的研究手记.md`,`# 和${char().name}的研究手记\n\n累计专注：${p.minutes} 分钟\n\n${p.memories.map(m=>`## ${m.title}\n${m.date}\n\n${m.text}`).join('\n\n')}\n\n## 专注记录\n${p.sessions.map(s=>`- ${s.date} · ${s.category} · ${s.minutes} 分钟`).join('\n')}`,'text/markdown');}
function showDialog(html,kind){dialogKind=kind;$('#dialogBody').innerHTML=html;const d=$('#dialog');if(!d.open)d.showModal();d.scrollTop=0;}
function closeDialog(){$('#dialog').close();dialogKind='';}
function openChat(){const id=uid(),p=profile();if(!p.chat.length){const r=replyFor('chat');S.update(s=>s.profiles[id].chat.push({role:'assistant',text:r.line,action:r.action}));}showDialog(`<h2 class="modal-title" id="dialogTitle">留一会儿，和${esc(char().name)}说说话</h2><p class="modal-sub">这里是有情境回应的本地陪伴对话。聊聊进度、疲惫或想念，他会记得这一段日常。</p><div class="chat-history" id="chatHistory" aria-live="polite"></div><div class="chat-prompts">${char().prompts.map(x=>`<button data-prompt="${esc(x.intent)}">${esc(x.label)}</button>`).join('')}</div><form class="chat-form" id="chatForm"><input id="chatInput" maxlength="300" placeholder="我今天读论文读到有点迷茫……" aria-label="想对他说的话" required><button class="primary" type="submit">发送 ${icon('arrow')}</button></form><p class="small muted" style="font-size:9px;margin-top:12px">原创情境脚本 · 不调用 AI 服务 · 不生成科研结论</p>`,'chat');renderChat();$('#chatForm').onsubmit=e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;$('#chatInput').value='';chatSend(text);};$('#dialogBody').querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>chatSend(b.textContent,b.dataset.prompt));}
function renderChat(){const h=$('#chatHistory');if(!h)return;h.innerHTML=profile().chat.slice(-40).map(m=>`<div class="chat-bubble ${m.role==='user'?'user':''}">${m.action?`<small>${esc(m.action)}</small>`:''}${esc(m.text)}</div>`).join('');h.scrollTop=h.scrollHeight;}
function chatSend(text,forced){let intent=forced||'chat';if(!forced){if(/累|困|难受|焦虑|崩溃|烦|不想|压力/.test(text))intent='tired';else if(/卡|不懂|不会|失败|实验|论文|文献|报错/.test(text))intent='stuck';else if(/完成|写完|做完|成功|进展/.test(text))intent='finish';else if(/想你|喜欢|抱|牵|亲/.test(text))intent=S.state().settings.romance?'hand':'encourage';else if(/开始|准备|学习|加油|催/.test(text))intent='start';else if(/水|渴/.test(text))intent='water';}let r={...replyFor(intent)};const task=profile().tasks.find(t=>!t.done);if(intent==='stuck'&&task){const step=task.steps.find(st=>!st.done);r.line+=` 先回到「${task.title}」${step?`，眼下只做这一小步：${step.text}`:'，把最不确定的问题写成一句话'}。`;}else if(intent==='finish'&&/完成|写完|做完/.test(text)){r.line+=' 这份进展值得记下来。去手记里亲手勾掉它吧。';}else if(intent==='chat'&&!forced){r.line=uid()==='qiyu'?'这句话我收到了。想让我安静陪着你，还是一起看看今天卡住的地方？':'嗯，我在听。你可以说说今天最费力的一件事，也可以先在这里坐一会儿。';r.action='认真听你说完';}S.update(s=>{const p=s.profiles[s.selected];p.chat.push({role:'user',text},{role:'assistant',text:r.line,action:r.action});p.chat=p.chat.slice(-100);});S.rewardInteraction('conversation');renderChat();updateStats();setDialogue(r);}
function openHelp(){const r=replyFor('stuck');setDialogue(r);showDialog(`<h2 class="modal-title" id="dialogTitle">卡住了，我们就把问题变小</h2><p class="modal-sub">${esc(r.line)}<br>先选择现在最接近的处境，带着一个具体动作回到桌前。</p><div class="template-list">${templates.map((t,i)=>`<button data-help-template="${i}">${esc(t.name)}<small>${esc(t.steps[0])}</small></button>`).join('')}</div><p class="small muted" style="line-height:1.9">试着写下：我想知道什么？目前的证据是什么？还差哪一步才能验证？<br>这里陪你组织思路，具体结论仍由文献与实验来回答。</p>`,'help');$('#dialogBody').querySelectorAll('[data-help-template]').forEach(b=>b.onclick=()=>openTaskForm(+b.dataset.helpTemplate));}
let restTimer=null;
function openRest(){respond('tired',false);const running=profile().timer&&!profile().timer.paused;if(running){S.pause();updateTimer();}showDialog(`<h2 class="modal-title" id="dialogTitle">休息也是今天的一部分</h2><p class="modal-sub">${esc(char().name)}把你面前的纸页轻轻合上。${running?'专注计时已暂停。':''}<br>喝口水，看看远处。你不用一直很有精神。</p><div class="celebrate"><div class="celebrate-symbol">☾</div><div class="timer-digits" id="restClock">05:00</div><p style="margin:12px 0 22px">给眼睛和肩膀一点空白</p><button class="primary full" id="restStart">开始五分钟休息</button><button class="text-btn" id="restChat">或者，和他聊一会儿 →</button></div>`,'rest');$('#restChat').onclick=openChat;$('#restStart').onclick=()=>{const end=Date.now()+5*60000;clearInterval(restTimer);$('#restStart').disabled=true;$('#restStart').textContent='好好休息，他会等你';restTimer=setInterval(()=>{const sec=Math.max(0,Math.ceil((end-Date.now())/1000));if(!$('#restClock')){clearInterval(restTimer);return;}$('#restClock').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec===0){clearInterval(restTimer);$('#restStart').disabled=false;$('#restStart').textContent=profile().timer?'休息好了，继续专注':'休息好了，回到桌前';$('#restStart').onclick=()=>{if(profile().timer?.paused)S.resume();closeDialog();respond('return',false);updateTimer();};if(soundOn)playChime();}},500);};}
function openGame(){if(profile().timer&&!profile().timer.paused){S.pause();updateTimer();toast('专注计时已暂停，休息一会儿。');}const symbols=['✦','☾','♡','❋'],cards=[...symbols,...symbols];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}let open=[],matched=new Set(),moves=0,busy=false;showDialog(`<h2 class="modal-title" id="dialogTitle">和他一起，找回散落的星光</h2><p class="modal-sub">翻开两张相同的星片。没有倒计时，慢慢来。<br>每天首次完成可以收获一点羁绊。</p><div class="row between"><span class="pill" id="gameScore">0 / 4 对星光</span><span class="small muted" id="gameMoves">翻找 0 次</span></div><div class="game-grid">${cards.map((_,i)=>`<button class="game-card" data-card="${i}" aria-label="翻开第 ${i+1} 张星片">✧</button>`).join('')}</div><p class="modal-sub" id="gameLine">${uid()==='qiyu'?'“看好了，这次我可不会放水……你先翻吧。”':'“记不住也没关系。我们可以再看一次。”'}</p><button class="secondary full" id="gameAgain" hidden>再玩一局</button>`,'game');$('#gameAgain').onclick=openGame;$('#dialogBody').querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const i=+b.dataset.card;if(busy||matched.has(i)||open.includes(i))return;b.textContent=cards[i];b.classList.add('open');b.setAttribute('aria-label',`第 ${i+1} 张：${cards[i]}`);open.push(i);if(open.length<2)return;moves++;$('#gameMoves').textContent=`翻找 ${moves} 次`;const [a,c]=open;if(cards[a]===cards[c]){matched.add(a);matched.add(c);[a,c].forEach(n=>{$(`[data-card="${n}"]`).classList.add('matched');$(`[data-card="${n}"]`).disabled=true;});open=[];$('#gameScore').textContent=`${matched.size/2} / 4 对星光`;if(matched.size===8){const reward=S.rewardInteraction('star-game');$('#gameLine').textContent=(uid()==='qiyu'?'“看来你也挺有天赋的。下次……还跟我一队？”':'“都找到了。嗯，和你一起很容易。”')+(reward.rewarded?' 羁绊 +2':'');$('#gameAgain').hidden=false;updateStats();}}else{busy=true;setTimeout(()=>{if(dialogKind!=='game')return;[a,c].forEach(n=>{const el=$(`[data-card="${n}"]`);if(el){el.textContent='✧';el.classList.remove('open');el.setAttribute('aria-label',`翻开第 ${n+1} 张星片`);}});open=[];busy=false;},850);}});}
function openSceneSettings(){showDialog(`<h2 class="modal-title" id="dialogTitle">今天，想待在哪种时光里？</h2><p class="modal-sub">为他身边的光线换一种心情。</p><div class="scene-picker">${[['studio','sun','午后暖光'],['night','moon','深夜相伴'],['sea','leaf','海风微光']].map(([id,i,t])=>`<button data-scene-choice="${id}" class="${id===sceneMode?'active':''}">${icon(i)}<br>${t}</button>`).join('')}</div>`,'scene');$('#dialogBody').querySelectorAll('[data-scene-choice]').forEach(b=>b.onclick=()=>{sceneMode=b.dataset.sceneChoice;$('#scene').dataset.scene=sceneMode;setPlace();closeDialog();toast('光线换好了，位置还是给你留着。');});}
function toggleImmersive(){immersive=!immersive;document.body.classList.toggle('immersive',immersive);$('#immersiveToggle').setAttribute('aria-label',immersive?'退出沉浸模式':'进入沉浸模式');}
async function toggleSound(){try{if(soundOn){soundNodes.forEach(n=>{try{n.stop();}catch(_){}});soundNodes=[];soundOn=false;if(soundCtx)await soundCtx.suspend();}else{const AC=window.AudioContext||window.webkitAudioContext;if(!AC){toast('这个浏览器暂不支持环境音。');return;}soundCtx=soundCtx||new AC();await soundCtx.resume();const seconds=5,buffer=soundCtx.createBuffer(1,soundCtx.sampleRate*seconds,soundCtx.sampleRate),d=buffer.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=(last+Math.random()*.04-.02)/1.02;d[i]=last*3;}const source=soundCtx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=soundCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;const gain=soundCtx.createGain();gain.gain.value=.26;source.connect(filter);filter.connect(gain);gain.connect(soundCtx.destination);source.start();soundNodes.push(source);soundOn=true;}S.update(s=>s.settings.sound=soundOn);$('#soundToggle').innerHTML=icon(soundOn?'sound':'mute');$('#soundToggle').setAttribute('aria-label',soundOn?'关闭海浪环境音':'播放海浪环境音');toast(soundOn?'海浪环境音已开启':'环境音已关闭');}catch(_){toast('环境音暂时无法播放，请再点一次试试。');}}
function playChime(){if(!soundCtx)return;[523.25,659.25,783.99].forEach((f,i)=>{const o=soundCtx.createOscillator(),g=soundCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(0,soundCtx.currentTime+i*.14);g.gain.linearRampToValueAtTime(.07,soundCtx.currentTime+i*.14+.03);g.gain.exponentialRampToValueAtTime(.001,soundCtx.currentTime+i*.14+1.2);o.connect(g);g.connect(soundCtx.destination);o.start(soundCtx.currentTime+i*.14);o.stop(soundCtx.currentTime+i*.14+1.3);});}
function openSettings(){const st=S.state();showDialog(`<h2 class="modal-title" id="dialogTitle">按你喜欢的方式相伴</h2><p class="modal-sub">Bedi 与祁煜、Zhai 与沈星回拥有各自独立的进度。本版存档保存在当前浏览器，导出后可在另一台设备导入。</p><label class="settings-row"><span>亲近一点的日常<small>开启牵手等亲密日常回应；关闭后改为温柔陪学。剧情仍可自主选择。</small></span><input type="checkbox" id="romanceSetting" ${st.settings.romance?'checked':''}></label><label class="settings-row"><span>人物动态与轻动画<small>关闭后停留在人物画面，适合安静学习。</small></span><input type="checkbox" id="motionSetting" ${st.settings.motion?'checked':''}></label><div class="settings-row"><span>当前存档状态<small>${S.persistence?'已在此设备保存。刷新页面可恢复暂停或进行中的计时。':'浏览器存储不可用或存档不兼容。请先导出原存档备份，避免丢失。'}</small></span>${icon(S.persistence?'check':'download')}</div><div class="settings-actions"><button class="secondary" id="exportSave">${icon('download')} 导出完整存档</button><button class="secondary" id="importSave">导入存档</button><input id="importFile" type="file" accept="application/json,.json" hidden></div><p class="small muted" style="font-size:10px;line-height:1.9">原来的 Firebase 奶茶、金币和养成记录仍在「奶茶小铺」里，未被覆盖。本版新剧情、计时和手记使用独立本机存档。</p>`,'settings');$('#romanceSetting').onchange=e=>{S.update(s=>s.settings.romance=e.target.checked);toast(e.target.checked?'亲近日常已开启':'已切换成温柔陪学');};$('#motionSetting').onchange=e=>{S.update(s=>s.settings.motion=e.target.checked);playVideo();};$('#exportSave').onclick=()=>download(`深空来信-存档-${new Date().toISOString().slice(0,10)}.json`,S.exportData(),'application/json');$('#importSave').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){toast('存档文件过大，请选择本平台导出的 JSON。');return;}const text=await file.text();let parsed;try{parsed=JSON.parse(text);}catch(_){toast('这不是可读取的 JSON 存档，原进度未改变。');return;}showDialog(`<h2 class="modal-title" id="dialogTitle">用这份存档继续旅程？</h2><p class="modal-sub">导入会替换此设备的新版陪伴进度。请先保存当前存档。格式与数据会在确认后完整检查，检查失败不会覆盖。</p><div class="form-actions"><button class="secondary" id="backupBeforeImport">先导出当前存档</button><button class="primary" id="confirmImport">确认导入</button></div>`,'import');$('#backupBeforeImport').onclick=()=>download('深空来信-导入前备份.json',S.exportData(),'application/json');$('#confirmImport').onclick=()=>{const r=S.importData(JSON.stringify(parsed));if(!r.ok){toast(`导入未完成：${r.error}`);return;}closeDialog();taskDraft='';taskId=null;applyCharacter();updateStats();updateTimer();renderSubview();toast('存档已恢复，欢迎回到这里。');};};}
function download(filename,content,type){const blob=new Blob([content],{type:`${type};charset=utf-8`}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openAbout(){showDialog(`<h2 class="modal-title" id="dialogTitle">让普通日常，也值得期待</h2><p class="modal-sub">深空来信是一份《恋与深空》同人陪伴体验。祁煜与沈星回的人物动态、形象素材来自游戏官方网站，相关权利属于原权利人。</p><div class="settings-row"><span>人物形象<small>官方人物片段自然轮播，也可以留在喜欢的一幕。采用预制动态与本地交互效果，非可操控的实时 3D 模型。</small></span></div><div class="settings-row"><span>故事与对话<small>12 章原创同人支线与情境脚本，不代表官方剧情；聊天不接入生成式 AI 或角色原声。</small></span></div><div class="settings-row"><span>你的进度<small>本版记录在本机。原版双人奶茶系统仍可从「奶茶小铺」打开。</small></span></div><div class="settings-actions"><a class="secondary" href="https://deepspace.papegames.com/news/4" target="_blank" rel="noopener">祁煜 · 官方介绍 ↗</a><a class="secondary" href="https://deepspace.papegames.com/news/2" target="_blank" rel="noopener">沈星回 · 官方介绍 ↗</a><a class="text-btn" href="assets/SOURCES.md" target="_blank">素材来源清单 ↗</a><a class="text-btn" href="assets/clips/SOURCES.md" target="_blank">动态镜头来源 ↗</a></div>`,'about');}
window.addEventListener('companion-storage-error',()=>{toast('暂时无法写入本机存档，请在设置中导出备份。');const status=$('#saveStatus');if(status)status.textContent='暂未能保存 · 请导出备份';});
window.addEventListener('companion-change',event=>{
 // Local actions already update their own controls; only another tab replaces
 // the displayed profile here, so typing and local dialogs are not rerendered.
 if(event.detail?.source!=='storage'||!$('#scene'))return;
 const switched=$('#scene').dataset.character!==uid(),timer=profile().timer;
 // Dialog callbacks and queued results may still belong to the previous save.
 pendingResults.length=0;
 if($('#dialog').open)closeDialog();
 $('#dialogBody').replaceChildren();
 clearInterval(restTimer);restTimer=null;
 taskDraft='';taskId=timer?.taskId||null;
 category=timer?.category||'科研';duration=timer?timer.durationMs/60000:25;
 $('#customDuration').value='';
 lastReply='';lastNudge=Date.now();
 applyCharacter(false);updateStats();updateTimer();renderSubview();
 toast(switched?`已同步另一个页面的选择：${char().name}。`:'已同步另一个页面的最新进度。');
});
mount();loadSceneClips();setInterval(checkTimers,500);checkTimers();
})();
